return {
	require("plugins.auto-sync"),
	require("plugins.autocomplete"),
	require("plugins.copilot"),
	require("plugins.copilot"),
	require("plugins.debugger"),
	require("plugins.edit-helpers"),
	require("plugins.formatting"),
	require("plugins.git-stuff"),
	require("plugins.harpoon"),
	require("plugins.linting"),
	require("plugins.lsp"),
	require("plugins.luasnip"),
	require("plugins.multiline-navigation"),
	require("plugins.neo-tree"),
	require("plugins.neodev"),
	require("plugins.sessions"),
	require("plugins.smooth-scroll"),
	require("plugins.telescope"),
	require("plugins.testing"),
	require("plugins.theme"),
	require("plugins.treesitter"),
	require("plugins.windows"),
	require("plugins.trouble"),
	require("plugins.search-replace"),

	require("plugins.junk"),
}
